--******************************************************************
--出庫一覧(親)
--******************************************************************
SELECT
    inout_datetime,
    work_no,
    parts_no,
    parts_name,
    old_new_structure_name,
    --dimensions,
    shipping_division_name,
    SUM(inout_quantity) AS inout_quantity,
    SUM(inout_quantity) AS inout_quantity_value,
    issue_quantity,
    issue_quantity AS issue_quantity_value,
    SUM(inout_quantity * unit_price) AS issue_monney,
    SUM(inout_quantity * unit_price) AS issue_monney_parent_value,
    currency_name,
    currency_name AS currency_name_parent,
    unit_digit,
    currency_digit,
    unit_round_division,
    currency_round_division,
    parts_id,
    job_structure_id,
    parts_location_id,
    parts_factory_id,
    CONVERT(varchar, work_no) + '_' + CONVERT(varchar, old_new_structure_id) AS nest_key,
    model_type
FROM
    target
GROUP BY
    inout_datetime,
    work_no,
    parts_no,
    parts_name,
    old_new_structure_name,
    --dimensions,
    shipping_division_name,
    issue_quantity,
    currency_name,
    unit_digit,
    currency_digit,
    unit_round_division,
    currency_round_division,
    parts_id,
    job_structure_id,
    parts_location_id,
    parts_factory_id,
    CONVERT(varchar, work_no) + '_' + CONVERT(varchar, old_new_structure_id),
    model_type