//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonWebTemplate.Models.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_USER_AUTH_SHORI_V
    {
        public string USERID { get; set; }
        public string CONDUCTID { get; set; }
        public short AUTHKBN { get; set; }
    }
}
