//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonSTDUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonSTDUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _111200006 {
            get {
                return ResourceManager.GetString("111200006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _111350001 {
            get {
                return ResourceManager.GetString("111350001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   計画保全支援システム(英語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _911090006 {
            get {
                return ResourceManager.GetString("911090006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _911260003 {
            get {
                return ResourceManager.GetString("911260003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _911430002 {
            get {
                return ResourceManager.GetString("911430002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _911430004 {
            get {
                return ResourceManager.GetString("911430004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。システム管理者に問い合わせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _941040004 {
            get {
                return ResourceManager.GetString("941040004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   許可されてないURLからのアクセスです。(英語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _941070006 {
            get {
                return ResourceManager.GetString("941070006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SiteMinderログインページが見つかりません。(英語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _941110002 {
            get {
                return ResourceManager.GetString("941110002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB接続に失敗しました。(英語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _941190004 {
            get {
                return ResourceManager.GetString("941190004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードを入力してください。(英語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _941260028 {
            get {
                return ResourceManager.GetString("941260028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーを入力してください。(英語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _941370003 {
            get {
                return ResourceManager.GetString("941370003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン認証処理に失敗しました。(英語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _941430003 {
            get {
                return ResourceManager.GetString("941430003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン認証に失敗しました。ユーザー権限がありません。(英語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _941430004 {
            get {
                return ResourceManager.GetString("941430004", resourceCulture);
            }
        }
    }
}
