INSERT INTO ma_history_failure(
    [history_failure_id]
    ,[history_id]
    ,[machine_id]
    ,[equipment_id]
    ,[maintenance_site]
    ,[maintenance_content]
    ,[phenomenon_structure_id]
    ,[phenomenon_note]
    ,[failure_cause_structure_id]
    ,[failure_cause_note]
    ,[failure_cause_personality_structure_id]
    ,[failure_cause_personality_note]
    ,[treatment_measure_structure_id]
    ,[treatment_measure_note]
    ,[failure_status]
    ,[failure_cause_addition_note]
    ,[previous_situation]
    ,[recovery_action]
    ,[improvement_measure]
    ,[system_feed_back]
    ,[lesson]
    ,[failure_note]
    ,[failure_analysis_structure_id]
    ,[failure_personality_factor_structure_id]
    ,[failure_personality_class_structure_id]
    ,[treatment_status_structure_id]
    ,[necessity_measure_structure_id]
    ,[measure_plan_date]
    ,[measure_class1_structure_id]
    ,[measure_class2_structure_id]
    ,[follow_flg]
    ,[follow_plan_date]
    ,[follow_content]
    ,[follow_completion_date]
    ,[used_days_machine]
    ,[update_serialid]
    ,[insert_datetime]
    ,[insert_user_id]
    ,[update_datetime]
    ,[update_user_id]
    ,[work_record]
) OUTPUT inserted.history_failure_id
VALUES(
    NEXT VALUE FOR seq_ma_history_failure_history_failure_id
    ,@HistoryId
    ,@MachineId
    ,@EquipmentId
    ,@MaintenanceSite
    ,@MaintenanceContent
    ,@PhenomenonStructureId
    ,@PhenomenonNote
    ,@FailureCauseStructureId
    ,@FailureCauseNote
    ,@FailureCausePersonalityStructureId
    ,@FailureCausePersonalityNote
    ,@TreatmentMeasureStructureId
    ,@TreatmentMeasureNote
    ,@FailureStatus
    ,@FailureCauseAdditionNote
    ,@PreviousSituation
    ,@RecoveryAction
    ,@ImprovementMeasure
    ,@SystemFeedBack
    ,@Lesson
    ,@FailureNote
    ,@FailureAnalysisStructureId
    ,@FailurePersonalityFactorStructureId
    ,@FailurePersonalityClassStructureId
    ,@TreatmentStatusStructureId
    ,@NecessityMeasureStructureId
    ,@MeasurePlanDate
    ,@MeasureClass1StructureId
    ,@MeasureClass2StructureId
    ,@FollowFlg
    ,@FollowPlanDate
    ,@FollowContent
    ,@FollowCompletionDate
    ,@UsedDaysMachine
    ,@UpdateSerialid
    ,@InsertDatetime
    ,@InsertUserId
    ,@UpdateDatetime
    ,@UpdateUserId
    ,@WorkRecord
);
