insert into com_bat_sch ( 
    ip_address,
    conductid,
    pgmid,
    formno,
    exec_date,
    exec_time,
    user_id,
    exec_seq,
    status,
    ret_cd,
    ret_msg,
    req_datetime,
    run_datetime,
    condition,
    optioninfo,
    exectime,
    extkbn1,
    extkbn2,
    extkbn3,
    extstr1,
    extstr2,
    extstr3,
    extnum1,
    extnum2,
    extnum3,
    extval1,
    extval2,
    extval3,
    biko,
    delflg,
    inpid,
    inpprocid,
    updid,
    updprocid
) values ( 
    /*IpAddress*/,
    /*ConductId*/,
    /*ConductId*/,
    0,
    to_char(timestamp 'now', 'YYYYMMDD'),
    to_char(timestamp 'now', 'HH24MISS'),
    /*UserId*/,
    1,
    0,      -- ステータス0:要求
    null,   -- 結果コードは登録の時点でNULL
    'バッチ起動を要求しました。',
    to_char(timestamp 'now', 'YYYY/MM/DD HH24:MI:SS'),    -- 要求時刻
    null,   -- 実行開始時間
    /*Condition*/null,
    null,
    null,   -- 実行時間(秒)
    /*Extkbn1*/null,
    /*Extkbn2*/null,
    null,
    /*Extstr1From*/null,
    /*Extstr1To*/null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    '',     -- 備考
    0,      -- 削除フラグ
    /*UserId*/,
    /*ConductId*/,
    /*UserId*/,
    /*ConductId*/
);
