INSERT INTO ln_long_plan(
    long_plan_id,
    subject,
    location_structure_id,
    job_structure_id,
    subject_note,
    person_id,
    person_name,
    work_item_structure_id,
    budget_management_structure_id,
    budget_personality_structure_id,
    maintenance_season_structure_id,
    purpose_structure_id,
    work_class_structure_id,
    treatment_structure_id,
    facility_structure_id,
    update_serialid,
    insert_datetime,
    insert_user_id,
    update_datetime,
    update_user_id
) OUTPUT inserted.long_plan_id
VALUES(
    NEXT VALUE FOR seq_ln_long_plan_long_plan_id,
    @Subject,
    @LocationStructureId,
    @JobStructureId,
    @SubjectNote,
    @PersonId,
    (SELECT display_name FROM ms_user WHERE user_id = @PersonId),
    @WorkItemStructureId,
    @BudgetManagementStructureId,
    @BudgetPersonalityStructureId,
    @MaintenanceSeasonStructureId,
    @PurposeStructureId,
    @WorkClassStructureId,
    @TreatmentStructureId,
    @FacilityStructureId,
    @UpdateSerialid,
    @InsertDatetime,
    @InsertUserId,
    @UpdateDatetime,
    @UpdateUserId
)
