INSERT INTO ms_item_extension(
    [item_id]
    ,[sequence_no]
    ,[extension_data]
    ,[update_serialid]
    ,[insert_datetime]
    ,[insert_user_id]
    ,[update_datetime]
    ,[update_user_id]
)
VALUES(
    @ItemId
    ,@SequenceNo
    ,@ExtensionData
    ,@UpdateSerialid
    ,@InsertDatetime
    ,@InsertUserId
    ,@UpdateDatetime
    ,@UpdateUserId
)
